- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.inputrc:
    ~/.gnupg/gpg.conf:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.jupyter/jupyter_notebook_config.py: jupyter/jupyter_notebook_config.py
    ~/.jupyter/nbconfig/notebook.json: jupyter/notebook.json
    ~/.local/share/jupyter/nbextensions: jupyter/nbextensions
    ~/.pythonrc:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    jupyter/nbextensions/
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
