- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.inputrc:
    ~/.gnupg/dirmngr.conf: gnupg/dirmngr.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.pythonrc:
    ~/.screenrc:
    ~/.shell:
    ~/.config/.tmux: tmux/plugins
    ~/.tmux.conf: tmux/tmux.conf
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule sync --recursive
    # the following have to run after linking ~/.gitconfig
    - git update-submodules
    - >
      git cleanall -f
      shell/plugins/
      zsh/plugins/
